#!/bin/bash
# Project Executor - Summary Generation Script
# Generates executive summary after project completion

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

PLANNING_DIR="$PROJECT_ROOT/docs/planning"
TASK_PLAN="$PLANNING_DIR/task-plan.md"
FINDINGS="$PLANNING_DIR/findings.md"
PROGRESS="$PLANNING_DIR/progress.md"
REFERENCES="$PLANNING_DIR/references.md"
REPORTS_DIR="$PLANNING_DIR/reports"

DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)

# Ensure reports directory exists
mkdir -p "$REPORTS_DIR"

# Extract project name from task-plan.md
PROJECT_NAME=$(head -1 "$TASK_PLAN" | sed 's/^# Task: //')

# Count phases and completion
count_phases() {
    grep -c "^### Phase [0-9]" "$TASK_PLAN" || echo "0"
}

count_completed_phases() {
    grep -A3 "^### Phase" "$TASK_PLAN" | grep -c "Complete" || echo "0"
}

# Count sessions
count_sessions() {
    grep -c "^### Session" "$PROGRESS" || echo "0"
}

# Count success criteria
count_criteria() {
    grep -c "^\- \[" "$TASK_PLAN" | head -1 || echo "0"
}

count_completed_criteria() {
    grep -c "^\- \[x\]" "$TASK_PLAN" || echo "0"
}

# Extract decisions made
extract_decisions() {
    sed -n '/^## Decisions Log/,/^## /p' "$TASK_PLAN" | grep "^| D" | head -10
}

# Extract key findings
extract_key_findings() {
    sed -n '/^## Summary/,/^## /p' "$FINDINGS" | tail -n +2 | head -10
}

# Extract files modified (from references.md)
extract_files() {
    grep "^\| \`" "$REFERENCES" | head -20
}

# Generate the summary
generate_summary() {
    local total_phases=$(count_phases)
    local completed_phases=$(count_completed_phases)
    local total_sessions=$(count_sessions)
    local total_criteria=$(count_criteria)
    local completed_criteria=$(count_completed_criteria)

    cat << EOF
# Execution Summary: $PROJECT_NAME

**Generated**: $DATE $TIME
**Status**: $([ "$completed_phases" = "$total_phases" ] && echo "Complete" || echo "Partial")

## Overview

| Metric | Value |
|--------|-------|
| Total Phases | $total_phases |
| Completed Phases | $completed_phases |
| Sessions | $total_sessions |
| Success Criteria Met | $completed_criteria / $total_criteria |

## Goal
$(sed -n '/^## Goal/,/^## /p' "$TASK_PLAN" | head -n -1 | tail -n +2)

## Phases Completed

$(sed -n '/^## Phases/,/^## /p' "$TASK_PLAN" | grep -A5 "^### Phase" | grep -B1 "Complete")

## Key Decisions

$(extract_decisions)

## Key Findings

$(extract_key_findings)

## Files Modified

$(extract_files)

## Lessons Learned

### What Worked Well
- [To be filled by Claude based on execution experience]

### What Could Be Improved
- [To be filled by Claude based on blockers encountered]

### Recommendations for Similar Projects
- [To be filled by Claude based on patterns observed]

## Session History

$(grep -A10 "^### Session" "$PROGRESS" | head -50)

---

*This summary was generated by the Claude Project Executor.*
EOF
}

# Archive function
archive_project() {
    local archive_name="${PROJECT_NAME// /-}-$DATE"
    local archive_dir="$PLANNING_DIR/archive/$archive_name"

    mkdir -p "$archive_dir"
    cp "$TASK_PLAN" "$archive_dir/"
    cp "$FINDINGS" "$archive_dir/"
    cp "$PROGRESS" "$archive_dir/"
    cp "$REFERENCES" "$archive_dir/"

    if [ -f "$REPORTS_DIR/execution-summary.md" ]; then
        cp "$REPORTS_DIR/execution-summary.md" "$archive_dir/"
    fi

    echo "Project archived to: $archive_dir"
}

# Command handling
case "${1:-generate}" in
    generate)
        generate_summary > "$REPORTS_DIR/execution-summary.md"
        echo "Summary generated: $REPORTS_DIR/execution-summary.md"
        ;;
    print)
        generate_summary
        ;;
    archive)
        archive_project
        ;;
    full)
        generate_summary > "$REPORTS_DIR/execution-summary.md"
        echo "Summary generated: $REPORTS_DIR/execution-summary.md"
        archive_project
        ;;
    *)
        echo "Usage: $0 {generate|print|archive|full}"
        echo ""
        echo "Commands:"
        echo "  generate  - Generate summary to reports/execution-summary.md"
        echo "  print     - Print summary to stdout"
        echo "  archive   - Archive project to archive/ folder"
        echo "  full      - Generate summary and archive"
        exit 1
        ;;
esac
