@echo off
setlocal enabledelayedexpansion

title Simple Claude Conductor - Setup

echo.
echo ========================================
echo   Simple Claude Conductor - Setup
echo ========================================
echo.

:: Check if START_HERE.md exists
if not exist "START_HERE.md" (
    echo ERROR: START_HERE.md not found!
    echo Please make sure you're running this from the project folder.
    echo.
    pause
    exit /b 1
)

echo Reading your settings from START_HERE.md...
echo.

:: Initialize variables with defaults
set "I_HAVE_SUBSCRIPTION=YES"
set "API_KEY="
set "PROJECT_NAME=My Project"
set "PROJECT_DESCRIPTION="
set "ASK_QUESTIONS=YES"
set "MODEL=SONNET"
set "MODEL_PLANNING=OPUS"
set "MODEL_HIGH=OPUS"
set "MODEL_MEDIUM=SONNET"
set "MODEL_LOW=HAIKU"
set "RUN_TESTS=NO"
set "TYPECHECK=NO"
set "LINT=NO"

:: Parse START_HERE.md - simple line-by-line parsing
for /f "usebackq tokens=1,* delims=:" %%a in ("START_HERE.md") do (
    set "key=%%a"
    set "value=%%b"

    :: Trim spaces from key (leading and trailing)
    for /f "tokens=* delims= " %%c in ("!key!") do set "key=%%c"
    :: Also trim trailing spaces from key
    if defined key (
        for /l %%i in (1,1,50) do if "!key:~-1!"==" " set "key=!key:~0,-1!"
    )

    :: Trim leading spaces from value
    if defined value (
        for /f "tokens=* delims= " %%c in ("!value!") do set "value=%%c"
    )
    :: Also trim trailing spaces from value
    if defined value (
        for /l %%i in (1,1,50) do if "!value:~-1!"==" " set "value=!value:~0,-1!"
    )

    :: Match known keys (case insensitive) - check for exact match after trimming
    if /i "!key!"=="I_HAVE_SUBSCRIPTION" (
        if defined value set "I_HAVE_SUBSCRIPTION=!value!"
    )
    if /i "!key!"=="API_KEY" (
        if defined value set "API_KEY=!value!"
    )
    if /i "!key!"=="PROJECT_NAME" (
        if defined value set "PROJECT_NAME=!value!"
    )
    if /i "!key!"=="ASK_QUESTIONS" (
        if defined value set "ASK_QUESTIONS=!value!"
    )
    if /i "!key!"=="MODEL" (
        if defined value set "MODEL=!value!"
    )
    if /i "!key!"=="MODEL_PLANNING" (
        if defined value set "MODEL_PLANNING=!value!"
    )
    if /i "!key!"=="MODEL_HIGH" (
        if defined value set "MODEL_HIGH=!value!"
    )
    if /i "!key!"=="MODEL_MEDIUM" (
        if defined value set "MODEL_MEDIUM=!value!"
    )
    if /i "!key!"=="MODEL_LOW" (
        if defined value set "MODEL_LOW=!value!"
    )
    if /i "!key!"=="RUN_TESTS" (
        if defined value set "RUN_TESTS=!value!"
    )
    if /i "!key!"=="TYPECHECK" (
        if defined value set "TYPECHECK=!value!"
    )
    if /i "!key!"=="LINT" (
        if defined value set "LINT=!value!"
    )
)

:: Display parsed settings
echo.
echo   YOUR SETTINGS:
echo.
echo     Project Name:     %PROJECT_NAME%
echo     Have Subscription: %I_HAVE_SUBSCRIPTION%
echo     Ask Questions:    %ASK_QUESTIONS%
echo     Default Model:    %MODEL%
echo.
echo   MODEL TIERS:
echo     Planning:         %MODEL_PLANNING%
echo     High Complexity:  %MODEL_HIGH%
echo     Medium Complexity:%MODEL_MEDIUM%
echo     Low Complexity:   %MODEL_LOW%
echo.
echo   QUALITY CHECKS:
echo     Run Tests:        %RUN_TESTS%
echo     Type Check:       %TYPECHECK%
echo     Lint:             %LINT%
echo.

:: Confirm before proceeding
echo Does this look correct?
echo.
choice /c YN /m "Continue with setup (Y/N)"
if errorlevel 2 (
    echo.
    echo Setup cancelled. Please edit START_HERE.md and try again.
    echo.
    pause
    exit /b 0
)

echo.
echo ========================================
echo   Setting Up Your Project
echo ========================================
echo.

:: Convert models to lowercase for yaml
set "MODEL_LOWER=sonnet"
if /i "%MODEL%"=="HAIKU" set "MODEL_LOWER=haiku"
if /i "%MODEL%"=="OPUS" set "MODEL_LOWER=opus"

set "MODEL_PLANNING_LOWER=opus"
if /i "%MODEL_PLANNING%"=="HAIKU" set "MODEL_PLANNING_LOWER=haiku"
if /i "%MODEL_PLANNING%"=="SONNET" set "MODEL_PLANNING_LOWER=sonnet"

set "MODEL_HIGH_LOWER=opus"
if /i "%MODEL_HIGH%"=="HAIKU" set "MODEL_HIGH_LOWER=haiku"
if /i "%MODEL_HIGH%"=="SONNET" set "MODEL_HIGH_LOWER=sonnet"

set "MODEL_MEDIUM_LOWER=sonnet"
if /i "%MODEL_MEDIUM%"=="HAIKU" set "MODEL_MEDIUM_LOWER=haiku"
if /i "%MODEL_MEDIUM%"=="OPUS" set "MODEL_MEDIUM_LOWER=opus"

set "MODEL_LOW_LOWER=haiku"
if /i "%MODEL_LOW%"=="SONNET" set "MODEL_LOW_LOWER=sonnet"
if /i "%MODEL_LOW%"=="OPUS" set "MODEL_LOW_LOWER=opus"

:: Convert yes/no to true/false
set "ASK_Q_BOOL=true"
if /i "%ASK_QUESTIONS%"=="NO" set "ASK_Q_BOOL=false"

set "TESTS_BOOL=false"
if /i "%RUN_TESTS%"=="YES" set "TESTS_BOOL=true"

set "TYPE_BOOL=false"
if /i "%TYPECHECK%"=="YES" set "TYPE_BOOL=true"

set "LINT_BOOL=false"
if /i "%LINT%"=="YES" set "LINT_BOOL=true"

:: Update project.yaml
echo [1/5] Updating configuration...

> project.yaml (
    echo # Simple Claude Conductor Configuration
    echo # Generated by INITIALIZE_MY_PROJECT.bat
    echo.
    echo version: "1.0"
    echo.
    echo project:
    echo   name: "%PROJECT_NAME%"
    echo   description: "A project using Simple Claude Conductor"
    echo.
    echo execution:
    echo   default_model: "%MODEL_LOWER%"
    echo   bypass_permissions: true
    echo   interrupt_for_questions: %ASK_Q_BOOL%
    echo   max_auto_phases: 10
    echo   generate_summary: true
    echo   test_first: false
    echo.
    echo # Safety gates - prevent runaway execution
    echo safety:
    echo   max_files_per_phase: 20
    echo   max_iterations_per_task: 5
    echo   require_checkpoint_every: 3
    echo   stop_on_repeated_errors: 3
    echo   max_total_files: 100
    echo.
    echo quality_gates:
    echo   run_tests: %TESTS_BOOL%
    echo   typecheck: %TYPE_BOOL%
    echo   lint: %LINT_BOOL%
    echo.
    echo # Model selection by task complexity
    echo # planning: Used for generating plans, orchestration decisions
    echo # high: Architecture, security, complex debugging
    echo # medium: Standard implementation, testing, refactoring
    echo # low: Docs, formatting, simple file ops, exploration
    echo models:
    echo   planning: "%MODEL_PLANNING_LOWER%"
    echo   high: "%MODEL_HIGH_LOWER%"
    echo   medium: "%MODEL_MEDIUM_LOWER%"
    echo   low: "%MODEL_LOW_LOWER%"
    echo.
    echo paths:
    echo   planning_dir: "docs/planning"
    echo   reports_dir: "docs/planning/reports"
    echo   archive_dir: "docs/planning/archive"
    echo.
    echo hooks:
    echo   mcp_reminder: true
    echo   branch_protection: true
    echo   file_guard: true
    echo   findings_reminder: true
)
echo       Done!

:: Update STATUS.md
echo [2/5] Creating status file...

> STATUS.md (
    echo # Project Status: %PROJECT_NAME%
    echo.
    echo **Last Updated**: %date%
    echo.
    echo ---
    echo.
    echo ## 👉 WHAT TO DO NEXT
    echo.
    echo **Setup Complete!** Your project is initialized and ready.
    echo.
    echo **Your Next Step:**
    echo.
    echo 1. ^(Optional^) Add reference files to `File_References_For_Your_Project\` folder
    echo    - Sample files, docs, screenshots, or examples
    echo    - Skip this if you don't have reference materials
    echo.
    echo 2. Double-click `RUN_PROJECT.bat` to start Claude
    echo.
    echo 3. When Claude starts, type: **"Generate a plan"**
    echo.
    echo ---
    echo.
    echo ## Quick Status
    echo.
    echo ^| Item ^| Status ^|
    echo ^|------^|--------^|
    echo ^| Project Initialized ^| Yes ✓ ^|
    echo ^| Claude Installed ^| Yes ✓ ^|
    echo ^| Ready to Start ^| Yes ✓ ^|
    echo.
    echo ---
    echo.
    echo ## Project Workflow
    echo.
    echo Here's what happens when you run the project:
    echo.
    echo 1. You run `RUN_PROJECT.bat`
    echo 2. Claude starts in the terminal
    echo 3. You say "Generate a plan" - Claude creates a plan
    echo 4. You say "Execute the plan" - Claude builds your project
    echo 5. Check `output\` folder for generated files
    echo 6. Check this file ^(STATUS.md^) for progress updates
    echo.
    echo ---
    echo.
    echo ## Progress Log
    echo.
    echo Claude will update this section as work progresses.
    echo Check back here anytime to see what's been completed!
)
echo       Done!

:: Update Questions file
echo [3/5] Creating questions file...

> Questions_For_You.md (
    echo # Questions For You
    echo.
    echo **Status**: No questions yet
    echo.
    echo ---
    echo.
    echo When Claude has questions about your project, they will appear below.
    echo.
    echo How to answer:
    echo 1. Read each question
    echo 2. Type your answer below the question
    echo 3. Save this file
    echo 4. Go back to the terminal and press Enter to continue
    echo.
    echo ---
    echo.
    echo ## Questions
    echo.
    echo No questions yet - Claude will add questions here when needed.
    echo.
    echo ---
    echo.
    echo Do not want to answer? Just press Enter in the terminal and Claude will make reasonable assumptions.
)
echo       Done!

:: Check Claude installation
echo [4/5] Checking Claude installation...

where claude >nul 2>&1
if %errorlevel% neq 0 (
    echo.
    echo ========================================
    echo   WARNING: Claude CLI Not Found
    echo ========================================
    echo.
    echo Claude Code CLI is not installed on this computer.
    echo.
    echo To install it:
    echo   1. Install Node.js from https://nodejs.org/
    echo   2. Open a new command prompt
    echo   3. Run: npm install -g @anthropic-ai/claude-code
    echo.
    echo After installing, run RUN_PROJECT.bat to start.
    echo.
    goto :success
)

echo       Claude CLI found!

:: Trust this directory so users don't get prompted
echo.
echo [5/5] Configuring trust settings...
claude config add trustedDirectories "%CD%" >nul 2>&1
if %errorlevel% equ 0 (
    echo       Directory trusted - no prompts when starting!
) else (
    echo       Note: Could not auto-trust directory.
    echo       You may see a trust prompt when running Claude.
)

:: Handle authentication for subscription users
if /i "%I_HAVE_SUBSCRIPTION%"=="YES" (
    echo.
    echo You chose to use your Claude subscription.
    echo.
    choice /c YN /m "Do you need to log in to Claude (Y/N)"
    if errorlevel 2 (
        echo       Skipping login - assuming already logged in.
    ) else (
        echo.
        echo Opening Claude login...
        echo A browser window should open. Sign in and return here.
        echo.
        call claude login
        echo.
        echo If login was successful, you are ready to go!
    )
)

:success
echo.
echo.
echo ========================================
echo        SETUP COMPLETE!
echo ========================================
echo.
echo Your project "%PROJECT_NAME%" is ready!
echo.
echo ========================================
echo   OPTIONAL: Add Reference Files
echo ========================================
echo.
echo Do you have sample files, docs, or examples?
echo Put them in: File_References_For_Your_Project\
echo.
echo (Skip this if you don't have reference files)
echo.
echo ========================================
echo   NEXT STEP: Double-click RUN_PROJECT.bat
echo ========================================
echo.
echo Or type RUN_PROJECT.bat here and press Enter.
echo.
echo When Claude starts, type: Generate a plan
echo.
echo ========================================
echo.
echo Press any key to close this window...
pause >nul
